### ISSUE TITLE
Use non–breaking space in sample content

### ISSUE THREAD

**Issue by oleq** [CKEditor5/ckeditor5.github.io#11]
I.e. to avoid wrapping "5" in CKEditor 5 to the new line, which looks odd.

https://en.wikipedia.org/wiki/Non-breaking_space

**Comment by Reinmar** [comment]
Yeah, we need to fix that because, as you must've seen yourself, this looks pretty bad:

![screen shot 2016-08-12 at 16 40 40](https://cloud.githubusercontent.com/assets/156149/17626005/a1a56370-60ab-11e6-9409-e7f587358bf7.png)

**Comment by Reinmar** [comment]
Will be fixed in 1c768f51b9e88b8cd54fc06bca91284a48c2eeee.
