### ISSUE TITLE
Disable focus outline glow on editable

### ISSUE THREAD

**Issue by fredck** [CKEditor5/ckeditor5.github.io#14]
In Chrome, the editable part of the editor gets outlined on focus. It looks like buggy because of it. Better to style it to be disabled.

![image](https://cloud.githubusercontent.com/assets/630060/18380475/d7b0cc5c-7677-11e6-8f62-72aa49498cb9.png)

**Comment by Reinmar** [comment]
Isn't it a classic creator's issue?

**Comment by fredck** [comment]
Well, I don't know... maybe it's a CKEditor 5 UI issue?

**Comment by fredck** [comment]
Anyway, provided a simple PR to workaround it here. Much probably it is worth to opening an issue in the proper place as well, to fix it for good.
