### ISSUE TITLE
Prepare sample for v0.3.0 release

### ISSUE THREAD

**Issue by oleq** [CKEditor5/ckeditor5.github.io#16]
The new features implemented in 0.3.0 should have their showcase in the sample.

**Comment by Reinmar** [comment]
I pushed all the things to branch iteration3. Could you take a look on it, @oleq?

**Comment by oleq** [comment]
Yep. I'll take a look.

**Comment by oleq** [comment]
Looks good to me 👍

**Comment by oleq** [comment]
BTW: Are you sure the 0.3.0 date is right? Oct the 4th?

**Comment by Reinmar** [comment]
I took it from GH. It's the tag date.

**Comment by oleq** [comment]
Alright then. I think it's OK to release it.
