### ISSUE TITLE
The logo is too small

### ISSUE THREAD

**Issue by Reinmar** [CKEditor5/ckeditor5.github.io#2]
I'm not joking – it can be missed, because "Developer Preview" is much bigger.

Besides, I'd consider changing the line "Developer Preview" to "CKEditor 5 v0.1.0 – Developer Preview", although if the logo becomes bigger that may not be necessary any more.

**Comment by Reinmar** [comment]
BTW. I see that some of you don't agree with making the logo bigger. Don't you think that the 'Developer Preview (v0.1.0)' text is just too big and stands out in such a way that at first you don't know what project it is? Of course, you can learn that in the next second, but I still feel that visual hierarchy is wrong. This and the separation of the logo by using a background makes you think that "CKEditor" is just a brand and all below is a standalone website within that brand. While this is CKEditor's website.

**Comment by fredck** [comment]
IMHO, I just feel that (1) it doesn't look bad in any case and (2) this was a conscious idea of the designers who proposed the layout so I would trust on their opinion because of (1).

**Comment by Reinmar** [comment]
It's not one man's job to design a website and asses the result, hence the feedback. My feeling is the user's feeling, though highly unrepresentative :D. So in such a case feedback really matters. Especially, that we look on this for too long now.

Anyway, 1:1 so far.

**Comment by oleq** [comment]
The original size and placement of the logo and hence the field of focus for visitors was my conscious decision and I think it does its job.
