### ISSUE TITLE
"TM" is messed up in logo

### ISSUE THREAD

**Issue by fredck** [CKEditor5/ckeditor5.github.io#3]
Following #2, the logo got messed up. IMHO it is way too big, but the really important point is that the "TM" mark is not aligned :/

**Comment by vokiel** [comment]
Temporary we removed the logo in #4

**Comment by oleq** [comment]
I'm completely lost why the initial header design has been wiped out:

![image](https://cloud.githubusercontent.com/assets/1099479/16917569/6ef8fff2-4d02-11e6-912e-71ad17ebcc15.png)

Though it wasn't the official v5 logo, it was a clear reference to CKEditor product line. Any ideas what exactly went wrong and what to do to fix it?

**Comment by Reinmar** [comment]
The logo must be brought back. It was a hot fix while you were away.

**Comment by oleq** [comment]
But I'm still puzzled, because #2 and #4 didn't specify precisely why it has been removed.

**Comment by Reinmar** [comment]
AFAIU, after the logo was made bigger (see #2), the "TM" got misplaced. For some reason the logo was totally removed instead of reverting the change. Is that right?

**Comment by oleq** [comment]
I reverted the changes and brought back the logo. It's a little bit bigger now but it corresponds with the original design which was, IMO, more subtle and tidy.
