### ISSUE TITLE
Alpha 1 blog post link 404

### ISSUE THREAD

**Issue by CanRau** [CKEditor5/ckeditor5.github.io#36]
> First alpha version 🎉🎉🎉
> Find out more in the CKEditor 5 v1.0.0 first alpha blog post

links to https://ckeditor5.github.io/TODO which results in 404

can't wait to read it^^

congratulations to the first alpha!!! 🎉🎉🎉🎉🎉🎉🎉🎉🎉 👍 👍 🥇

**Comment by Reinmar** [comment]
The blog post is out https://github.com/ckeditor/ckeditor5-design/issues/181

Thanks!

**Comment by CanRau** [comment]
just realised that I might have been a little too fast^^
