### ISSUE TITLE
Prepare sample for v0.2.0 release

### ISSUE THREAD

**Issue by oleq** [CKEditor5/ckeditor5.github.io#9]
Requires https://github.com/CKEditor5/ckeditor5.github.io/issues/8.

**Comment by Reinmar** [comment]
I've been looking at the text that we use in the editor and I think that to make it up to date, we can simply update the number of closed tickets (being a sum of all of them), the iteration number ("This is the <Nth> developer preview"), number of years and of course version :).

**Comment by oleq** [comment]
I created v0.2.0 branch and corresponding PR. Please take a look on https://github.com/CKEditor5/ckeditor5.github.io/pull/12#issue-171356074.

**Comment by Reinmar** [comment]
Idea: Let's copy the previous version this website to `/version/0.1.0/` and let's add there the next ones later on. This will help in checking for regressions (whether an issue has just appeared or is an old one). WDYT?

**Comment by Reinmar** [comment]
(Remember about excluding those old versions from Google)

**Comment by oleq** [comment]
Why not? I'm OK with it.
